apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- include "tiny-pianist.labels" $ | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      {{- range .Values.deployments }}
      {{- $componentName := printf "%s-%s" (include "tiny-pianist.fullname" $) (.name) }}
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $componentName }}
            port:
              number: 80
      {{- end }}
